spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: my-spring-boot
            client-secret: A5rGhmZIUCF1lsX5RNjeUTl22IyU0boO
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/auth/realms/test-realm
            user-name-attribute: preferred_username
