spring:
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: <springboot-keycloak＞
            client-secret: <Clients > springboot-keycloak, Secret＞
            authorization-grant-type: authorization_code
            scope: openid
        provider:
          keycloak:
            issuer-uri: <https://keycloak-<project>.apps.*.openshiftapps.com/auth/realms/<realm>>
            user-name-attribute: preferred_username
